apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend
  namespace: microservices-demo
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend
  namespace: microservices-demo
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend2
  namespace: microservices-demo 